### ISSUE TITLE
Default VPN connection

### ISSUE THREAD

**Issue by bkiziuk** [saucecontrol/VpnDialerPlus#1]
Is there any way to set one of connections as the default (or maybe use the last used one) in the dropdown box?
I have a single VPN connection that I would like to use but every time the application is started, the box is empty and the connection must be picked-up from the list.

**Comment by saucecontrol** [comment]
That sounds good.  I'd accept a PR for that ;)

**Comment by bkiziuk** [comment]
Looks like I'm not qualified to prepare it ;-) But anyway, I find this piece of app very useful.
